{{- if .Values.hub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-landing
  namespace: hub
  labels:
    app: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
        - name: nginx
          image: hakeemraj/hub-landing:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: {{ include "kenyaemr-hub.fullname" . }}-landing
---
apiVersion: v1
kind: Service
metadata:
  name: hub-landing
  namespace: hub
spec:
  selector:
    app: hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hub-ingress
  namespace: hub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hub.domain }}
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: hub-landing
                port:
                  number: 80
{{- end }}
