apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.tenant.name }}-backend
