apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ .Values.tenant.name }}-frontend
