apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kenyaemr-ingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-kenyaemr
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.tenant.name }}.local
      http:
        paths:
          - path: /openmrs/spa(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.tenant.name }}-frontend
                port:
                  number: 80
          - path: /openmrs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.tenant.name }}-backend
                port:
                  number: 8080
