{{- if .Values.tenant.enableRestoreJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.tenant.name }}-init-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-restore
          image: hakeemraj/kenyaemr-db-restore:{{ .Values.tenant.dbRestoreImageTag }}
          env:
            - name: DB_HOST
              value: {{ .Values.tenant.dbHost }}
            - name: DB_USER
              value: {{ .Values.tenant.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.tenant.dbPassword }}
            - name: DB_NAME
              value: {{ .Values.tenant.dbSchema }}
{{- end }}
