apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tenant.name }}-runtime-config
  namespace: {{ .Release.Namespace }}
data:
  runtime.properties: |
    connection.url=jdbc:mysql://{{ .Values.tenant.dbHost }}/{{ .Values.tenant.dbSchema }}?autoReconnect=true&useSSL=false
    connection.username={{ .Values.tenant.dbUser }}
    connection.password={{ .Values.tenant.dbPassword }}
    module.allow_web_admin=true
    auto_update_database=true
    create_tables=false
