apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.name }}-svc
spec:
  selector:
    app: {{ .Values.tenant.name }}
  ports:
    - name: frontend
      port: 80
      targetPort: 80
    - name: backend
      port: 8080
      targetPort: 8080
